### ISSUE TITLE
оператор = в my_unique_ptr не является exception-safe

### ISSUE THREAD

**Issue by alexey-malov** [apolukhin/course-nimble_cpp#2]
https://github.com/apolukhin/course-nimble_cpp/blob/8059da2a78b958b108c9e1ada1b7dc1f17126c69/container_4.hpp#L29-L33
если new выбросит исключение, то data_ будет указывать на удалённый адрес, и повторный delete в деструкторе приведёт к undefined behavior.
Кроме того, нет защиты от самоприсваивания - также будет UB при разыменовании удалённого указателя.
Лучше исправить на что-то такое:
```c++
    my_unique_ptr& operator=(const my_unique_ptr& p) {
        if (&p != this)
        {
            auto data = (p.data_ ? new int{*p.data_} : nullptr);
            delete data_;
            data_ = data;
        }
        return *this;
    }
```

**Comment by igor-sadchenko** [comment]
Либо вместо этих двух
```cpp
    my_unique_ptr& operator=(const my_unique_ptr& p) {
        delete data_;
        data_ = (p.data_ ? new int{*p.data_} : nullptr);
        return *this;
    }

    my_unique_ptr& operator=(my_unique_ptr&& p) {
        std::swap(data_, p.data_);
        return *this;
    }
```
сделать один
```cpp
    my_unique_ptr& operator=(my_unique_ptr p) {
        std::swap(data_, p.data_);
        return *this;
    }
```

**Comment by alexey-malov** [comment]
Такой "универсальный" оператор присваивания нельзя будет сделать noexcept в "оптимизированной" версии. А тут за счёт noexcept был в бенчмарке прирост раза в 1,5-2.

**Comment by apolukhin** [comment]
Можно "универсальный" оператор сделать noexcept, т.к. noexcept будет относиться только к содержимому функции между фигурными скобками и конструктор временного объекта под noexcept не попадёт. Но это немного непривычная конструкция...
